build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

style:
  ThrowsCount:
    max: 5
  MaxLineLength:
    maxLineLength: 140
  ReturnCount:
    max: 4
  UnusedPrivateMember:
    active: true
  WildcardImport:
    active: true
  MagicNumber:
    ignoreNumbers: ['-1', '0', '1', '2', '3', '4', '100', '1000']
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: true
    ignoreNamedArgument: true
    ignoreExtensionFunctions: true
    excludes: ['**/test/**', '**/testFixtures/**', '**/*Test.kt', '**/ui/**']

complexity:
  LongMethod:
    threshold: 80
    ignoreAnnotated: ['Composable']
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 10
    ignoreDefaultParameters: true
  TooManyFunctions:
    thresholdInFiles: 25
    thresholdInClasses: 25
    ignorePrivate: true
  CyclomaticComplexMethod:
    threshold: 20
  NestedBlockDepth:
    threshold: 5

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable', 'Test']
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9_]*'

exceptions:
  TooGenericExceptionCaught:
    active: true
    allowedExceptionNameRegex: '_|(ignore|expected).*'
  SwallowedException:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true
